### ISSUE TITLE
WEEK 4 - TODO's

### ISSUE THREAD

**Issue by Skac121245** [Skac121245/Robort#10]
- [ ] Change Name
- [ ] Change Icon
- [ ] Change title of index.html
- [ ] Delete Match Schedule tab b/c its on home
- [ ] Make CSS for nav's
- [ ] Add PickList Element
- [ ] Add selecter for event codes in match table
- [ ] Figure out a way to have options and text inputs on select's
- [ ] Fix the bug in canvas where you have to select the same match twice when switching tabs
- [ ] No more erasing team numbers
- [ ] Make "clear" just clear the drawings, not the team numbers
- [ ] Make the tab switch more noticeable (make font bigger or smt else)
