### ISSUE TITLE
DCMP - TODO's

### ISSUE THREAD

**Issue by Skac121245** [Skac121245/Robort#21]
- [x] fix checklist "add one more bug"
- [x] make offline mode available to teams list element
- [x] make offline mode available to canvas
- [ ] make sections in checklist
- [x] update config with checkboxes for teleop attributes
- [x] add autos to config (images and names)
- [ ] match table isn't displaying semifinal numbers correctly
- [x] when saving canvas, make the background the image of the feild
- [x] update all nav's
- [ ] make images for autos bigger
- [x] add robot name to config
- [ ] Add a dark mode
